app = "level10"

kill_signal = "SIGTERM"
kill_timeout = 5

[metrics]
port = 9091
path = "/metrics"

[env]

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "5s"
    port = "4000"
    restart_limit = 1
    timeout = "1s"
