# fly.toml app configuration file generated for level10 on 2023-05-24T23:44:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "level10"
primary_region = "dfw"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "1s"
    grace_period = "10s"
    restart_limit = 1

[metrics]
  port = 9091
  path = "/metrics"
