---
kind: Service
apiVersion: v1
metadata:
  name: level10
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "aab3f570-144b-4eda-8820-e1891c55974f"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
  labels:
    app: level10
spec:
  type: LoadBalancer
  selector:
    app: level10
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: level10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: level10
  template:
    metadata:
      labels:
        app: level10
    spec:
      serviceAccountName: internal-pod
      imagePullSecrets:
        - name: registry-dnsbty
      containers:
        - name: level10
          image: registry.digitalocean.com/dnsbty/level10:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: level10
                  key: databaseUrl
            - name: POOL_SIZE
              value: "2"
            - name: PORT
              value: "4000"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: level10
                  key: cookie
            - name: RELEASE_DISTRIBUTION
              value: "name"
            - name: RELEASE_NAME
              value: "level10@$(POD_IP)"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: level10
                  key: secretKeyBase
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: level10
                  key: sendgridApiKey
