---
kind: Job
apiVersion: batch/v1
metadata:
  name: level10-migrator
spec:
  template:
    metadata:
      labels:
        app: level10-migrator
    spec:
      containers:
      - name: level10-migrator
        image: registry.digitalocean.com/dnsbty/level10:{{IMAGE_TAG}}
        command: ["/app/bin/level10",  "eval", "Level10.Release.migrate"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: level10
                key: databaseUrl
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: level10
                key: secretKeyBase
      restartPolicy: Never
  backoffLimit: 4
