on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: registry.digitalocean.com/dnsbty/level10
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build container image
        run: docker build -t ${REGISTRY_URL}:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${REGISTRY_URL}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save dnsbty-k8s

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl set image deployments/level10 level10=${REGISTRY_URL}:$(echo $GITHUB_SHA | head -c7)

      - name: Verify deployment
        run: kubectl rollout status deployments/level10
